version: '3'

services:
  reverse-proxy:
    image: traefik:v2.11
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.http.address=:80
      - --entrypoints.mysql.address=:3306
      - --providers.docker.exposedbydefault=true
    ports:
      - "80:80"
      - "8080:8080"
      - "3306:3306"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: test_password
      MYSQL_DATABASE: course_catalog
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    volumes:
        - ./database/volume:/var/lib/mysql
    hostname: database.cc.localhost
    labels:
      - traefik.tcp.routers.mysql.entrypoints=mysql
      - traefik.tcp.routers.mysql.rule=HostSNI(`*`)
      - traefik.tcp.services.mysql.loadbalancer.server.port=3306
    ports:
      - 8001:3306

  api:
    image: php:8.3-apache
    container_name: api
    depends_on:
      - db
    volumes:
      - ./api/:/var/www/html/
    stdin_open: true
    tty: true
    hostname: api.cc.localhost
    labels:
      - traefik.http.routers.api.rule=Host(`api.cc.localhost`)
  front:
    image: php:8.3-apache
    container_name: front
    depends_on:
      - api
    volumes:
      - ./front_end/:/var/www/html/
    stdin_open: true
    tty: true
    hostname: api.cc.localhost
    labels:
      - traefik.http.routers.front.rule=Host(`cc.localhost`)
