swagger: "2.0"
info:
  description: "This is tech test task for Full stack developer"
  version: "1.0.0"
  title: "Course catalog"
host: api.cc.localhost
basePath: /
schemes: [http]
tags:
  - name: "categories"
    description: "Categories of courses"
  - name: "courses"
    description: "Courses"
paths:
  /categories:
    get:
      tags:
        - "categories"
      summary: "Get all categories"
      description: "Returns all categories"
      operationId: "getCategories"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Category"
  /categories/{id}:
    get:
      tags:
        - "categories"
      summary: "Get category by id"
      description: "Returns a category by id"
      operationId: "getCategoryById"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of category to return"
          required: true
          type: "string"
          format: "guid"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Category"
  /courses:
    get:
      tags:
        - "courses"
      summary: "Get all courses"
      description: "Returns all courses"
      operationId: "getCourses"
      produces:
        - "application/json"
      parameters:
        - name: "category_id"
          in: "query"
          description: "Filter by category id"
          required: false
          type: "string"
          format: "guid"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Course"
  /courses/{id}:
    get:
      tags:
        - "courses"
      summary: "Get course by id"
      description: "Returns a course by id"
      operationId: "getCourseById"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of course to return"
          required: true
          type: "string"
          format: "guid"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Course"
definitions:
    Category:
        type: "object"
        properties:
          id:
              type: "string"
              format: "guid"
          name:
              type: "string"
          description:
              type: "string"
          parent_id:
              type:
                - "null"
                - "string"
              format: "guid"
              description: "Parent category id"
          count_of_courses:
              type: "integer"
              format: "int32"
              description: "Count of courses in category including subcategories"
          created_at:
              type: "string"
              format: "date-time"
          updated_at:
              type: "string"
              format: "date-time"
    Course:
        type: "object"
        properties:
          id:
              type: "string"
              format: "guid"
          name:
              type: "string"
          description:
              type: "string"
          preview:
              type: "string"
              description: "URL to preview image"
          main_category_name:
              type: "string"
              description: "Main category name"
          created_at:
              type: "string"
              format: "date-time"
          updated_at:
              type: "string"
              format: "date-time"